config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reservations
  resources :vols
  resources :aeroports
  root 'vols#index'
  get "reservations/new/:numVol",to:'reservations#new'
  post "reservations/new/:numVol",to:'reservations#create'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/aeroport.rb
class Aeroport < ApplicationRecord

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vol.rb
class Vol < ApplicationRecord
  belongs_to :departure_aeroport, class_name: 'Aeroport'
  belongs_to :arrival_aeroport, class_name: 'Aeroport'
end

app/controllers/aeroports_controller.rb
class AeroportsController < ApplicationController
  before_action :set_aeroport, only: %i[ show edit update destroy ]

  # GET /aeroports or /aeroports.json
  def index
    @aeroports = Aeroport.all
  end

  # GET /aeroports/1 or /aeroports/1.json
  def show
  end

  # GET /aeroports/new
  def new
    @aeroport = Aeroport.new
  end

  # GET /aeroports/1/edit
  def edit
  end

  # POST /aeroports or /aeroports.json
  def create
    @aeroport = Aeroport.new(aeroport_params)

    respond_to do |format|
      if @aeroport.save
        format.html { redirect_to aeroport_url(@aeroport), notice: "Aeroport was successfully created." }
        format.json { render :show, status: :created, location: @aeroport }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aeroport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aeroports/1 or /aeroports/1.json
  def update
    respond_to do |format|
      if @aeroport.update(aeroport_params)
        format.html { redirect_to aeroport_url(@aeroport), notice: "Aeroport was successfully updated." }
        format.json { render :show, status: :ok, location: @aeroport }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aeroport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aeroports/1 or /aeroports/1.json
  def destroy
    @aeroport.destroy

    respond_to do |format|
      format.html { redirect_to aeroports_url, notice: "Aeroport was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aeroport
      @aeroport = Aeroport.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aeroport_params
      params.require(:aeroport).permit(:name, :libelle)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.where(user_id: current_user.id)
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    @reservation.vol_id = params[:vol_id]
    @flight  = Vol.find(params[:vol_id])
    respond_to do |format|
      format.html { render 'reservations/new'}
      format.json { render flight: @flight }
    end
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:vol_id, :user_id, :nb_passagers, :choix_place)
    end
end

app/controllers/vols_controller.rb
class VolsController < ApplicationController
  before_action :set_vol, only: %i[ show edit update destroy ]

  # GET /vols or /vols.json
  def index
    @pagy, @vols = pagy(Vol.all)
  end

  # GET /vols/1 or /vols/1.json
  def show
  end

  # GET /vols/new
  def new
    @vol = Vol.new
  end

  # GET /vols/1/edit
  def edit
  end

  # POST /vols or /vols.json
  def create
    @vol = Vol.new(vol_params)

    respond_to do |format|
      if @vol.save
        format.html { redirect_to vol_url(@vol), notice: "Vol was successfully created." }
        format.json { render :show, status: :created, location: @vol }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vols/1 or /vols/1.json
  def update
    respond_to do |format|
      if @vol.update(vol_params)
        format.html { redirect_to vol_url(@vol), notice: "Vol was successfully updated." }
        format.json { render :show, status: :ok, location: @vol }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vols/1 or /vols/1.json
  def destroy
    @vol.destroy

    respond_to do |format|
      format.html { redirect_to vols_url, notice: "Vol was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vol
      @vol = Vol.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def vol_params
      params.require(:vol).permit(:numero, :id_aeroport_depart, :id_aeroport_arrivee, :duree, :date_depart, :nb_place_economique, :nb_place_business)
    end
end

app/helpers/aeroports_helper.rb
module AeroportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/vols_helper.rb
module VolsHelper
end

app/views/aeroports/_aeroport.html.erb
<div id="<%= dom_id aeroport %>">
  <p>
    <strong>Name:</strong>
    <%= aeroport.name %>
  </p>

  <p>
    <strong>Libelle:</strong>
    <%= aeroport.libelle %>
  </p>

</div>

app/views/aeroports/_form.html.erb
<%= form_with(model: aeroport) do |form| %>
  <% if aeroport.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aeroport.errors.count, "error") %> prohibited this aeroport from being saved:</h2>

      <ul>
        <% aeroport.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :libelle, style: "display: block" %>
    <%= form.text_field :libelle %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/aeroports/edit.html.erb
<h1>Editing aeroport</h1>

<%= render "form", aeroport: @aeroport %>

<br>

<div>
  <%= link_to "Show this aeroport", @aeroport %> |
  <%= link_to "Back to aeroports", aeroports_path %>
</div>

app/views/aeroports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Aeroports</h1>

<div id="aeroports">
  <% @aeroports.each do |aeroport| %>
    <%= render aeroport %>
    <p>
      <%= link_to "Show this aeroport", aeroport %>
    </p>
  <% end %>
</div>

<%= link_to "New aeroport", new_aeroport_path %>

app/views/aeroports/new.html.erb
<h1>New aeroport</h1>

<%= render "form", aeroport: @aeroport %>

<br>

<div>
  <%= link_to "Back to aeroports", aeroports_path %>
</div>

app/views/aeroports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @aeroport %>

<div>
  <%= link_to "Edit this aeroport", edit_aeroport_path(@aeroport) %> |
  <%= link_to "Back to aeroports", aeroports_path %>

  <%= button_to "Destroy this aeroport", @aeroport, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <header>
      <div>
          <h1><%= link_to "Ub'air", "/", class: "title" %></h1>
        </div>

      <div class="link-menu">
        <ul>
          <li><%= link_to "Mes réservations", "/reservations" %></li> |
          <li><%= link_to "Vols", "/vols" %></li>
          <li><a href=""></a></li>
        </ul>
      </div>

       <div>
         <% if user_signed_in? %>
           Logged in as <strong><%= current_user.email %></strong>.
           <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
           <%= button_to "Deconnexion", destroy_user_session_path, :method => :delete, :data => {:no_turbolink => true} %>

         <% else %>
           <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
           <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
         <% end %>
       </div>
    </header>
    <div class="main">
      <%= yield %>
    </div>






    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <div>
    <%= form.label :id_vol, style: "display: block" %>
    <div class="id_vol"><%=@flight.id %></div>
  </div>
  <%= form.hidden_field :vol_id, value: @flight.id %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <div>
    <%= form.label :id_user, style: "display: block" %>
    <div class="id_user"><%=current_user.id%></div>
  </div>

  <div>
    <%= form.label :nb_passagers, style: "display: block" %>
    <%= form.number_field :nb_passagers %>
  </div>

  <div>
    <%= form.label "Place économique/place buisness", style: "display: block" %>
    <%= form.check_box :choix_place %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>">
  <p>
    <strong>Id vol:</strong>
    <%= reservation.vol_id %>
  </p>

  <p>
    <strong>Id user:</strong>
    <%= reservation.user_id %>
  </p>

  <p>
    <strong>Nb passagers:</strong>
    <%= reservation.nb_passagers %>
  </p>

  <p>
    <strong>Choix place:</strong>
    <%= reservation.choix_place %>
  </p>

</div>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Show this reservation", @reservation %> |
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reservations</h1>

<div id="reservations">
  <% @reservations.each do |reservation| %>
    <%= render reservation %>
    <p>
      <%= link_to "Show this reservation", reservation %>
    </p>
  <% end %>
</div>

<%= link_to "New reservation", new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reservation %>

<div>
  <%= link_to "Edit this reservation", edit_reservation_path(@reservation) %> |
  <%= link_to "Back to reservations", reservations_path %>

  <%= button_to "Destroy this reservation", @reservation, method: :delete %>
</div>

app/views/vols/_form.html.erb
<%= form_with(model: vol) do |form| %>
  <% if vol.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vol.errors.count, "error") %> prohibited this vol from being saved:</h2>

      <ul>
        <% vol.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :numero, style: "display: block" %>
    <%= form.number_field :numero %>
  </div>

  <div>
    <%= form.label :id_aeroport_depart, style: "display: block" %>
    <%= form.number_field :id_aeroport_depart %>
  </div>

  <div>

    <%= form.label :id_aeroport_arrivee, style: "display: block" %>
    <%= form.number_field :id_aeroport_arrivee %>
  </div>

  <div>
    <%= form.label :duree, style: "display: block" %>
    <%= form.number_field :duree %>
  </div>

  <div>
    <%= form.label :date_depart, style: "display: block" %>
    <%= form.datetime_field :date_depart %>
  </div>

  <div>
    <%= form.label :nb_place_economique, style: "display: block" %>
    <%= form.number_field :nb_place_economique %>
  </div>

  <div>
    <%= form.label :nb_place_business, style: "display: block" %>
    <%= form.number_field :nb_place_business %>
  </div>

  <div>
    <%=link_to "vol", action: "show", id: @vol%>
  </div>
<% end %>

app/views/vols/_vol.html.erb
<div id="<%= dom_id vol %>" class="vol">

  <div class="number">
    <strong>Numero:</strong>
    <div>
      <%= vol.numero %>
    </div>
  </div>

  <div class="voyage">
    <div class="depart">
        <div class="aeroport">
          <%= vol.departure_aeroport.libelle %>
        </div>
        <div class="date">
          <%= vol.date_depart.strftime("%d %B %Y  %H:%M") %>
        </div>
    </div>
    <div class="img-plane">
      <%= image_tag "plane.png" %>
    </div>
    <div class="arrivee">
      <div class="aeroport">
        <%= vol.arrival_aeroport.libelle %>
      </div>
      <div class="date">
        <%= (vol.date_depart + vol.duree.minutes).strftime("%d %B %Y  %H:%M") %>
      </div>
    </div>
  </div>

  <div class="vol-option">
    <%= link_to "Show this vol", vol %>
  </div>

  <p>
    <strong>Nb place business:</strong>
    <%= vol.nb_place_business %>
  </p>
  <div>
    <%=link_to "réserver", controller: :reservations, action: :new, vol_id: vol.id %>
  </div>
</div>

app/views/vols/edit.html.erb
<h1>Editing vol</h1>

<%= render "form", vol: @vol %>

<br>

<div>
  <%= link_to "Show this vol", @vol %> |
  <%= link_to "Back to vols", vols_path %>
</div>

app/views/vols/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vols</h1>

<div id="vols">
  <% @vols.each do |vol| %>
    <%= render vol %>

  <% end %>
</div>

<%= pagy_nav(@pagy).html_safe %>

app/views/vols/new.html.erb
<h1>New vol</h1>

<%= render "form", vol: @vol %>

<br>

<div>
  <%= link_to "Back to vols", vols_path %>
</div>

app/views/vols/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vol %>

<div>
  <%= link_to "Edit this vol", edit_vol_path(@vol) %> |
  <%= link_to "Back to vols", vols_path %>

  <%= button_to "Destroy this vol", @vol, method: :delete %>
</div>